### ISSUE TITLE
.pk1 files

### ISSUE THREAD

**Issue by codc3** [KenrickLance/Rep-Bot#1]
how can I edit or create a new "repList.pk1" file ??

I can not in any way edit the information in the .pk1 files I do not know this format and would like to know more about the study character!

![image](https://user-images.githubusercontent.com/25847896/36353334-0c493636-14a4-11e8-972d-ce5597c60314.png)

**Comment by KenrickLance** [comment]
Note that some peripheral features of the bot like playing music isn't fleshed out yet because i'm busy with school but i will still be working on the bot.
